services:
  mongodb:
    container_name: mongodb-wichat_es5b
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  llmservice:
    container_name: llmservice-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/llmservice:latest
    profiles: ["dev", "prod"]
    env_file:
      - .env
    build: 
      context: ./llmservice
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  wikidataservice:
    container_name: wikidataservice-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/wikidataservice:latest
    profiles: ["dev", "prod"]
    build: ./wikidataservice
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    
  gameservice:
    container_name: gameservice-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/gameservice:latest
    profiles: ["dev", "prod"]
    build: ./gameservice
    depends_on:
      - wikidataservice
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      WIKIDATA_SERVICE_URL: http://llmservice:8004 

  gatewayservice:
    container_name: gatewayservice-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
      - wikidataservice
      - gameservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      LLM_SERVICE_URL: http://llmservice:8003
      WIKIDATA_SERVICE_URL: http://llmservice:8004
      GAME_SERVICE_URL: http://llmservice:8005

  webapp:
    container_name: webapp-wichat_es5b
    image: ghcr.io/arquisoft/wichat_es5b/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - gatewayservice
      - gameservice
    ports:
      - "3000:3000"
    environment:
      GAME_SERVICE_URL: http://llmservice:8005

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_es5b
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_es5b
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
