ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Alcance y Contexto del Sistema


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****
endif::arc42help[]

=== Contexto de Negocio

Este apartado indica cómo se va a comunicar la aplicación con los diferentes actores y servicios:

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****
endif::arc42help[]

[plantuml,"Vision general",png]
----
@startuml
skinparam monochrome true
left to right direction

actor "Usuario"

node "WiChat" {
}

cloud "Wikidata" {
}

node "Mistral" {
}

"Usuario" --> "WiChat" : Interactúa
"WiChat" <--> "Wikidata" : Pide y recibe datos
"WiChat" <--> "Mistral" : Intercambia mensajes del usuario

@enduml
----

* Usuario

Persona real que utilizará la aplicación. Interactuará con ella eligiendo una de las múltiples respuestas que se le presentarán según la imagen utilizada.

* Wikidata

Base de datos general de donde obtendremos las imágenes y datos relacionados con ellas. La aplicación se comunica y obtiene información de Wikidata a través de su API.

* Mistral

Modelo de Lenguaje creado por Empathy. Es el modelo de lenguaje que usaremos para apoyar al usuario en caso de que necesite pistas.

=== Contexto Técnico

Este apartado indica cómo las diferentes partes de la aplicación se comunican entre sí:

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
endif::arc42help[]

[plantuml,"Vision general",png]
----
@startuml
skinparam monochrome true
left to right direction

actor "Usuario"

frame WiChat {
    node "Webapp"

    node "Gateway"

    node "User service"

    node "Auth service"

    node "LLM service"

    node "Query service"

    node "Game service"

    database "Mongo DB"
}

cloud "Wikidata"

cloud "Mistral"

"Usuario" --> "Webapp" : HTTP
"Webapp" <--> "Gateway" : HTTP
"Gateway" <--> "User service" : HTTP
"Gateway" <--> "Auth service" : HTTP
"Gateway" <--> "LLM service" : HTTP
"Gateway" <--> "Query service" : HTTP
"User service" <--> "Mongo DB" : HTTP
"Auth service" <--> "Mongo DB" : HTTP
"LLM service" <--> "Mistral" : HTTPS
"Query service" <--> "Wikidata" : HTTPS
"Game service" <--> "Gateway" : HTTP


@enduml
----

[cols="1,1,1"]
|===
|*Participantes*
|*Vía de comunicación*
|*Motivo de la comunicación*

|Usuario - Webapp
|HTTP
|Interacción con la aplicación

|Webapp - Gateway
|HTTP
|Intercambio de datos entre Frontend y Backend

|Gateway - User service
|HTTP
|Registro

|Gateway - Auth service
|HTTP
|Inicio de sesión

|Gateway - LLM service
|HTTP
|Chat en tiempo real

|Gateway - Query service
|HTTP
|Interacción con Wikidata

|Query service - Wikidata
|HTTPS
|Obtención de imágenes y datos

|User service - Mongo DB
|HTTP
|Registro

|Auth service - Mongo DB
|HTTP
|Inicio de sesión

|LLM service - Mistral
|HTTPS
|Chat en tiempo real

|Game service - Gateway
|HTTP
|Comunicación con la lógica
|===