ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Alcance y Contexto del Sistema


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
El alcance y contexto del sistema - como lo sugiere el nombre - delimita al sistema (es decir, el alcance) de todos sus
socios de comunicación (Usuarios y sistemas vecinos, es decir, el contexto del sistema). 
Con ello se especifican las interfaces externas.

Si es necesario, diferenciar el contexto de negocio (Entradas y salidas específicas del dominio) del contexto técnico
(canales, protocolos, hardware).

.Motivación
Las interfases de dominio y las interfases técnicas a los socios de comunicación son de los aspectos más críticos del sistema.
Se debe asegurar el entendimiento de ellos.

.Forma
Varias opciones:

* Diagramas de contexto
* Listas de socios de comunicación y sus interfases.
****
endif::arc42help[]

=== Contexto de Negocio

Este apartado indica cómo se va a comunicar la aplicación con los diferentes actores y servicios:

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
La especificación de *todos* los socios de comunicación (usuarios, sistemas, ...) con explicaciones de las entradas y salidas
específicas del dominio o interfases.
Opcionalmente puede agregar formatos específicos de dominio o protocolos de comunicación

.Motivación
Todas las partes interesadas deben entender que datos son intercambiados con el ambiente del sistema.

.Forma
Cualquier forma de diagramas que muestren al sistema como una caja negra y especifiquen las interfases de dominio a los
socios de comunicación.

De manera alternativa (o adicional) se puede utilizar una tabla.
El título de la tabla es el nombre del sistema, las tres columnas contienen el nombre del socio de comunicación, las
entradas y las salidas
****
endif::arc42help[]

[plantuml,"Contexto negocio",png]
----
@startuml
skinparam monochrome true
left to right direction

actor "Usuario"

node "WiChat" {
}

cloud "Wikidata" {
}

cloud "LLM" {
}

"Usuario" --> "WiChat" : Interactúa
"WiChat" <--> "Wikidata" : Pide y recibe datos
"WiChat" <--> "LLM" : Genera pistas para el usuario

@enduml
----

* Usuario

Persona real que utilizará la aplicación. Interactuará con ella eligiendo una de las múltiples respuestas que se le presentarán según la imagen utilizada.

* Wikidata

Base de datos general de donde obtendremos las imágenes y datos relacionados con ellas. La aplicación se comunica y obtiene información de Wikidata a través de su API.

* LLM

Modelo de Lenguaje utilizado para generar las pistas de la aplicación .Utilizamos dos LLMs distintos, Qwen y Mistral, creados por Empathy.

=== Contexto Técnico

Este apartado indica cómo las diferentes partes de la aplicación se comunican entre sí:

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Las interfases técnicas (medios de transmisión y canales) enlanzando al sistema con su ambiente. De manera adicional
el mapeo de las entradas/salidas específicas del dominio a los canales, es decir, una explicación acerca de que entrada/salida
utiliza cual canal.

.Motivación
Muchas partes relacionadas realizan decisiones arquitectónicas basadas en las interfases técnicas entre el sistema y 
su contexto. Especialmente los diseñadores de infraestructura o hardware deciden estas interfases técnicas.

.Forma
Por ejemplo, diagramas UML de despligue describiendo los canales a sistemas vecinos, junto con una tabla de 
mapeo mostrando las relaciones entre los canales y las entradas/salidas.
****
endif::arc42help[]

[plantuml,"Contexto tecnico",png]
----
@startuml
skinparam monochrome true
left to right direction

actor "Usuario"

frame WiChat {
    node "Webapp"

    node "GatewayService"

    node "UserService"

    node "AuthService"

    node "LLMService"

    node "WikidataService"

    node "GameService"

    node "StatsService"

    database "Users DB"

    database "History DB"

    database "Ranking DB"
}

cloud "Wikidata"

cloud "LLM"

"Usuario" --> "Webapp" : HTTP
"Webapp" <--> "GatewayService" : HTTP
"GatewayService" <--> "UserService" : HTTP
"GatewayService" <--> "AuthService" : HTTP
"GatewayService" <--> "LLMService" : HTTP
"GatewayService" <--> "GameService" : HTTP
"GatewayService" <--> "StatsService" : HTTP
"GameService" <--> "WikidataService" : HTTP
"StatsService" <--> "History DB" : HTTP
"StatsService" <--> "Ranking DB" : HTTP
"UserService" <--> "Users DB" : HTTP
"AuthService" <--> "Users DB" : HTTP

"LLMService" <--> "LLM" : HTTPS
"WikidataService" <--> "Wikidata" : HTTPS


@enduml
----

[cols="1,1,1"]
|===
|*Participantes*
|*Vía de comunicación*
|*Motivo de la comunicación*

|Usuario - Webapp
|HTTP
|Interacción con la aplicación

|Webapp - GatewayService
|HTTP
|Intercambio de datos entre Frontend y Backend

|GatewayService - UserService
|HTTP
|Registro de usuarios

|GatewayService - AuthService
|HTTP
|Inicio de sesión

|GatewayService - LLMService
|HTTP
|Generación de pistas

|GatewayService - GameService
|HTTP
|Interaccion con el juego

|GatewayService - StatsService
|HTTP
|Obtencion de estadisticas

|GameService - WikidataService
|HTTP
|Interacción con Wikidata

|WikidataService - Wikidata
|HTTPS
|Obtención de imágenes y datos de las preguntas

|StatsService - History DB
|HTTP
|Obtencion del historial del jugador

|StatsService - Ranking DB
|HTTP
|Obtencion del ranking global

|UserService - Users DB
|HTTP
|Registro de usuarios

|AuthService - Users DB
|HTTP
|Inicio de sesión

|LLMService - LLM
|HTTPS
|Generación de pistas
|===