ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Alcance y Contexto del Sistema


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Context and scope - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.


.Further Information

See https://docs.arc42.org/section-3/[Context and Scope] in the arc42 documentation.

****
endif::arc42help[]

=== Contexto de Negocio

Este apartado indica cómo se va a comunicar la aplicación con los diferentes actores y servicios:

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.

****
endif::arc42help[]

[plantuml,"Vision general",png]
----
@startuml
!pragma layout smenata
skinparam monochrome true
left to right direction

actor "Usuario"

node "WiChat" {
}

cloud "Wikidata" {
}

cloud "Mistral" {
}

"Usuario" <-- "WiChat" : Muestra imágenes, respuestas y un chat interactuable
"Usuario" --> "WiChat" : Interacciona con el chat y elige respuestas
"WiChat" <-- "Wikidata" : Recibe datos
"WiChat" --> "Mistral" : Envía los mensajes del usuario
"WiChat" <-- "Mistrtal" : Devuelve respuestas del LLM

@enduml
----

* Usuario

Persona real que utilizará la aplicación. Interactuará con ella eligiendo una de las múltiples respuestas que se le presentarán según la imagen utilizada.

* Wikidata

Base de datos general de donde obtendremos las imágenes y datos relacionados con ellas.

* Mistral

Modelo de Lenguaje creado por Empathy. Es el modelo de lenguaje que usaremos para apoyar al usuario en caso de que necesite pistas.

=== Contexto Técnico

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation which I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
endif::arc42help[]

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
