ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Alcance y Contexto del Sistema


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
El alcance y contexto del sistema - como lo sugiere el nombre - delimita al sistema (es decir, el alcance) de todos sus
socios de comunicación (Usuarios y sistemas vecinos, es decir, el contexto del sistema). 
Con ello se especifican las interfaces externas.

Si es necesario, diferenciar el contexto de negocio (Entradas y salidas específicas del dominio) del contexto técnico
(canales, protocolos, hardware).

.Motivación
Las interfases de dominio y las interfases técnicas a los socios de comunicación son de los aspectos más críticos del sistema.
Se debe asegurar el entendimiento de ellos.

.Forma
Varias opciones:

* Diagramas de contexto
* Listas de socios de comunicación y sus interfases.
****
endif::arc42help[]

=== Contexto de Negocio

Este apartado indica cómo se va a comunicar la aplicación con los diferentes actores y servicios:

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
La especificación de *todos* los socios de comunicación (usuarios, sistemas, ...) con explicaciones de las entradas y salidas
específicas del dominio o interfases.
Opcionalmente puede agregar formatos específicos de dominio o protocolos de comunicación

.Motivación
Todas las partes interesadas deben entender que datos son intercambiados con el ambiente del sistema.

.Forma
Cualquier forma de diagramas que muestren al sistema como una caja negra y especifiquen las interfases de dominio a los
socios de comunicación.

De manera alternativa (o adicional) se puede utilizar una tabla.
El título de la tabla es el nombre del sistema, las tres columnas contienen el nombre del socio de comunicación, las
entradas y las salidas
****
endif::arc42help[]

[plantuml,"Contexto negocio",png]
----
@startuml
skinparam monochrome true
left to right direction

actor "Usuario"

node "WiChat" {
}

cloud "Wikidata" {
}

node "Mistral" {
}

"Usuario" --> "WiChat" : Interactúa
"WiChat" <--> "Wikidata" : Pide y recibe datos
"WiChat" <--> "Mistral" : Intercambia mensajes del usuario

@enduml
----

* Usuario

Persona real que utilizará la aplicación. Interactuará con ella eligiendo una de las múltiples respuestas que se le presentarán según la imagen utilizada.

* Wikidata

Base de datos general de donde obtendremos las imágenes y datos relacionados con ellas.

* Mistral

Modelo de Lenguaje creado por Empathy. Es el modelo de lenguaje que usaremos para apoyar al usuario en caso de que necesite pistas.

=== Contexto Técnico

Este apartado indica cómo las diferentes partes de la aplicación se comunican entre sí:

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Las interfases técnicas (medios de transmisión y canales) enlanzando al sistema con su ambiente. De manera adicional
el mapeo de las entradas/salidas específicas del dominio a los canales, es decir, una explicación acerca de que entrada/salida
utiliza cual canal.

.Motivación
Muchas partes relacionadas realizan decisiones arquitectónicas basadas en las interfases técnicas entre el sistema y 
su contexto. Especialmente los diseñadores de infraestructura o hardware deciden estas interfases técnicas.

.Forma
Por ejemplo, diagramas UML de despligue describiendo los canales a sistemas vecinos, junto con una tabla de 
mapeo mostrando las relaciones entre los canales y las entradas/salidas.
****
endif::arc42help[]

[plantuml,"Contexto tecnico",png]
----
@startuml
skinparam monochrome true
left to right direction

actor "Usuario"

frame WiChat {
    node "Webapp"

    node "Gateway"

    node "User service"

    node "Auth service"

    node "LLM service"

    database "Mongo DB"
}

cloud "Wikidata"

cloud "Mistral"

"Usuario" --> "Webapp"
"Webapp" <--> "Gateway"
"Gateway" <--> "User service"
"Gateway" <--> "Auth service"
"Gateway" <--> "LLM service"
"User service" <--> "Mongo DB"
"Auth service" <--> "Mongo DB"
"LLM service" <--> "Mistral"
"Gateway" <--> "Wikidata"


@enduml
----

[cols="1,1,1"]
|===
|*Participantes*
|*Vía de comunicación*
|*Motivo de la comunicación*

|Usuario - Webapp
|HTTP
|Interacción con la aplicación

|Webapp - Gateway
|Por determinar
|Intercambio de datos entre Frontend y Backend

|Gateway - User service
|Por determinar
|Registro

|Gateway - Auth service
|Por determinar
|Inicio de sesión

|Gateway - LLM service
|Por determinar
|Chat en tiempo real

|Gateway - Wikidata
|HTTPS
|Obtención de imágenes y datos

|User service - Mongo DB
|Por determinar
|Registro

|Auth service - Mongo DB
|Por determinar
|Inicio de sesión

|LLM service - Mistral
|HTTPS
|Chat en tiempo real
|===