ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Vista de Ejecución


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
La vista de ejecución describe el comportamiento concreto y las interacciones de los bloques del sistema en forma de escenarios de las siguientes áreas:

* casos de uso o características importantes: ¿cómo los ejecutan los bloques?
* interacciones en interfaces externas críticas: ¿cómo cooperan los bloques con los usuarios y sistemas vecinos?
* operación y administración: lanzamiento, inicio, detención
* escenarios de error y excepciones

Nota: El criterio principal para la elección de los escenarios posibles (secuencias, flujos de trabajo) es su *relevancia arquitectónica*. *No* es importante describir un gran número de escenarios. En su lugar, deberías documentar una selección representativa.

.Motivación
Debes comprender cómo (instancias de) los bloques de construcción de tu sistema realizan su trabajo y se comunican en tiempo de ejecución.
Principalmente capturarás escenarios en tu documentación para comunicar tu arquitectura a las partes interesadas que tienen menos disposición o capacidad para leer y entender los modelos estáticos (vista de bloques, vista de despliegue).

.Formato
Existen muchas notaciones para describir escenarios, por ejemplo:

* lista numerada de pasos (en lenguaje natural)
* diagramas de actividad o diagramas de flujo
* diagramas de secuencia
* BPMN o EPCs (cadenas de procesos de eventos)
* máquinas de estados
* ...


.Más información

Observa https://docs.arc42.org/section-6/[Runtime View] en la documentacion de arc42.

****
endif::arc42help[]

=== <Registro de nuevo usuario>

Este diagrama de secuencia representa el flujo que tendra la peticion de un usuario para registrarse como nuevo usuario.

[plantuml,"Registro de nuevo usuario",png]
----
@startuml

actor Usuario
participant "WebApp" as WebApp
participant "GatewayService" as GatewayService
participant "UserService" as UserService
database "Base de datos" as BaseDatos

Usuario -> WebApp: Solicitar registro
WebApp -> GatewayService: Enviar solicitud de registro
GatewayService -> UserService: Reenviar solicitud de registro
UserService -> BaseDatos: Guardar datos del usuario
BaseDatos --> UserService: Confirmar almacenamiento
UserService --> GatewayService: Confirmar registro exitoso
GatewayService --> WebApp: Respuesta de registro exitoso
WebApp --> Usuario: Confirmar registro completado

@enduml
----

=== <Inicio de sesion>

Este diagrama de secuencia hace referencia a las llamadas entre los distintos objetos de la aplicacion web para que un usuario inicie sesion.

[plantuml,"Inicio de sesion",png]
----
@startuml

actor Usuario
participant "WebApp" as WebApp
participant "GatewayService" as GatewayService
participant "AuthService" as AuthService
database "Base de datos" as BaseDatos

Usuario -> WebApp: Solicitar inicio de sesión
WebApp -> GatewayService: Enviar credenciales
GatewayService -> AuthService: Validar credenciales
AuthService -> BaseDatos: Comprobar credenciales
BaseDatos --> AuthService: Respuesta de validación

alt Credenciales correctas
    AuthService --> GatewayService: Autenticación exitosa
    GatewayService --> WebApp: Respuesta exitosa
    WebApp --> Usuario: Confirmar inicio de sesión
else Credenciales incorrectas
    AuthService --> GatewayService: Autenticación fallida
    GatewayService --> WebApp: Respuesta fallida
    WebApp --> Usuario: Notificar error de inicio de sesión
end

@enduml
----

=== <Generacion de pregunta y respuestas>

Este diagrama de secuencia resume el flujo de la aplicación web para generar las preguntas y respuestas una vez iniciado el juego por parte del usuario.

[plantuml,"Generacion de pregunta",png]
----
@startuml

actor Usuario
participant "WebApp" as WebApp
participant "GatewayService" as GatewayService
participant "GameService" as GameService
participant "WikidataService" as WikidataService

Usuario -> WebApp: Iniciar juego
WebApp -> GatewayService: Solicitar pregunta
GatewayService -> GameService: Redirigir la peticion
GameService -> WikidataService: Enviar consultas SPARQL

WikidataService --> WikidataService: Comprobar si la respuesta está cacheada
alt Primera petición o respuesta no cacheada
alt Wikidata responde correctamente
    WikidataService --> WikidataService: Ejecutar consulta con SPARQL
    WikidataService --> GameService: Enviar respuesta consulta
    GameService -> GameService: Generar preguntas
    GameService --> GatewayService: Enviar preguntas
    GatewayService --> WebApp: Enviar preguntas
    WebApp --> Usuario: Mostrar pregunta
else Wikidata falla
    WikidataService --> GameService: Notificar error al ejecutar consulta
    GameService --> GatewayService: Notificar error al generar pregunta
    GatewayService --> WebApp: Notificar error
    WebApp --> Usuario: Notificar error
end
else Siguientes peticiones
     WikidataService --> GameService: Enviar respuesta cacheada
     GameService -> GameService: Generar preguntas
     GameService --> GatewayService: Enviar preguntas
     GatewayService --> WebApp: Enviar preguntas
     WebApp --> Usuario: Mostrar pregunta
end


@enduml
----

=== <Generación de una pista>

Este diagrama de secuencia representa cómo se genera una pista para una pregunta determinada tras ser solicitada por el usuario que está jugando.

[plantuml,"Generacion de pista",png]
----
@startuml

actor Usuario

Usuario -> WebApp: Solicita una nueva pista
WebApp -> GatewayService: Enviar solicitud de generación
GatewayService -> LLMService: Generar pista
LLMService --> GatewayService: Devolver pista generada
GatewayService --> WebApp: Respuesta con la pista
WebApp --> Usuario: Mostrar pista generada

@enduml
----

=== <Consulta de estadísticas>

Este diagrama de secuencia representa el flujo de la petición de un usuario que haya iniciado sesión en el sistema y quiera saber sus estadísticas de juego.

[plantuml,"Consulta de estadisticas",png]
----
@startuml

actor Usuario
participant "WebApp" as WebApp
participant "GatewayService" as GatewayService
participant "StatsService" as StatsService
database "Base de datos" as BaseDatos

Usuario -> WebApp: Solicitar estadísticas
WebApp -> GatewayService: Enviar solicitud de estadísticas
GatewayService -> StatsService: Consultar estadísticas
StatsService -> BaseDatos: Obtener datos estadísticos
BaseDatos --> StatsService: Devolver datos
StatsService --> GatewayService: Respuesta con estadísticas
GatewayService --> WebApp: Respuesta con estadísticas
WebApp --> Usuario: Mostrar estadísticas

@enduml
----