ifndef::imagesdir[:imagesdir: ../images]

[[section-deployment-view]]


== Vista de despliegue

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
La vista de despliegue describe:

. La infraestructura técnica usada para ejecutar el sistema, con elementos de infraestructura como locaciones geográficas,
ambientes, computadoras, procesadores, canales y topologías de red así como otros elementos de infraestructura.
. El mapeo de los bloques de construcción (software) en dichos elementos de infraestructura.

Comúnmente los sistemas son ejecutados en diferentes ambientes, por ejemplo, ambiente de desarrollo, de pruebas, de producción. En dichos casos deberían documentarse todos los ambientes relevantes.

Deberá documentarse la vista de despliegue de manera especial cuando el software se ejecute como un sistema distribuido
con mas de una computadora, procesador, servidor o contenedor o cuando se diseñen los procesadores y chips de hardware propios.

Desde una perspectiva de software es suficiente con capturar los elementos de la infraestructura necesarios para mostrar
el despliegue de los bloques de construcción. Los arquitectos de hardware pueden ir más alla y describir la infraestructura
a cualquier nivel de detalle que requieran.

.Motivación
El software no corre sin haardware.
El hardware subyacente puede influenciar el sistema o algunos conceptos entrecruzados. Por ende, es necesario conocer
la infraestructura.

.Forma
Quizá el más alto nivel de diagrama de despliegue esté contenido en la sección 3.2. como contexto técnico con la 
propia infraestructura como UNA caja negra. En esta sección se deberá realizar un acercamiento a ésta caja negra 
utilizando diagramas de despliegue adicionales:

* UML provee diagramas de despliegue para expresar la vista. Uselos, probablemente con diagramas anidados.
* Cuando las partes relacionadas de Hardware prefieran otro tipo de diagramas además de los diagramas de despliegue,
permítales usar cualquier tipo que permita mostrar los nodos y canales de la infraestructura.


.Más información

Ver https://docs.arc42.org/section-7/[Deployment View] en la documentación de arc42.

****
endif::arc42help[]

=== Nivel de Infraestructura 1

ifdef::arc42help[]
[role="arc42help"]
****
Describa (Usualmente en una combinación de diagramas, tablas y texto):

* La distribución del sistema en múltiples ubicaciones, ambientes, computadoras, procesadores, ... así como las
conexiones físicas entre ellos
* La motivación o justificación de importancia para la estructura de despliegue
* Características de Calidad y/o rendimiento de la infraestructura
* El mapeo de los artefactos de software a los elementos de la infraestructura.

Para múltiples ambientes o despliegues alternativos copie esta sección para todos los ambientes relevantes.
****
endif::arc42help[]

[plantuml, arquitectura, png]
----
@startuml


actor usuario

node Dispositivo{
    [Buscador] as buscador
}

node Azure{
    node Docker{
        node webapp-wichat_es5b{
            [Webapp] as webapp
        }

        node gatewayservice-wichat_es5b{
            [Gatewayservice] as gateway
        }

        node authservice-wichat_es5b{
            [Authservice] as authservice
        }

        node userservice-wichat_es5b{
            [Userservice] as userservice
        }

        node gameservice-wichat_es5b{
            [GameService] as gameservice
        }

        node wikidataservice-wichat_es5b{
            [WikidataService] as wikidataservice
        }

        node statsservice-wichat_es5b{
            [StatsService] as statsservice
        }

        node llmservice-wichat_es5b{
            [LLMService] as llmservice
        }

        node mongodb-wichat_es5b{
            database "userdb" as userdb
            database "game" as game
        }

    }
}

Cloud "Wikidata"
Cloud "LLM"

usuario --> buscador
buscador --> webapp
webapp --> gateway
gateway --> llmservice
llmservice --> LLM
gateway --> authservice
gateway --> userservice
gateway --> gameservice
gameservice --> wikidataservice
wikidataservice --> "Wikidata"
userservice --> userdb
authservice --> userdb
gateway --> statsservice
statsservice --> game

@enduml
----

Motivación::

En el anterior diagrama podemos ver que cada componente se encuentra encapsulado en un contenedor Docker, en los que se
encapsula el software para simplificar su despliegue. La interfaz de nuestra
aplicación se encuentra en Webapp, donde el usuario se conecta mediante un buscador desde su dispositivo.
La aplicación se conecta con los servicios internos de la aplicación mediante Gatewayservice, que distribuye
las llamadas de la aplicación entre el resto de los servicios de la misma. Nuestra aplicación también cuenta
con dos bases de datos, una en la que almacenamos los usuarios registrados y otra en la que guardamos el historial de sus partidas y el ránking global.




Características de calidad/rendimiento::

Gracias al uso de docker nuestro sistema es portable (podríamos cambiarlo de máquina y seguiría funcionando sin
muchos cambios) y escalable, ya que podemos crear nuevos contenedores y nuevas instancias en el caso de que sean
necesarias. También, gracias a que almacenamos la base de datos dentro de la misma máquina que nuestra aplicación,
las llamadas a la misma serán más rápidas que si se encontrase fuera de la misma.


Mapeo de los Bloques de Construcción a Infraestructura::
[options="header",cols="1,2"]
|===
| Bloque de Construcción | Infraestructura
| Azure | Es el servicio que va a hostear el servidor en el que estara almacenada nuestra aplicación
| WebApp | Es el frontend de nuestra aplicación
| Gatewayservice | Es el servicio mediante el cual llamamos al resto de los servicios internos de la aplicación
| Authservice | Es el servicio que se encarga de la autenticación de los usuarios
| Userservice | Es el servicio que se encarga de almacenar los usuarios registrados en la aplicación
| LLMService | Es el servicio que realiza las llamadas al LLM
| GameService | Es el servicio que maneja la lógica del juego
| WikidataService | Es el servicio que ejecuta las consultas a Wikidata
| StatsService | Es el servicio que gestiona las estadísticas de los jugadores y el ranking global del juego
| Database | Es la base de datos donde almacenaremos la información de los usuarios y las estadisticas de cada uno
| LLM | Es un modelo extenso de lenguaje localizado en un servidor ajeno al que accederemos mediante una API key
| Wikidata | Es una base de datos externa de la que extraemos la información para generar las preguntas
|===


