ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Decisiones de Diseño


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Decisiones arquitectónicas importantes, costosas, a larga escala o riesgosas incluyendo sus razonamientos.
Con "Decisiones" nos referimos a la elección de una alternativa basada en cierto criterio.

Se debe usar el juicio para decidir si una decisión arquitectónica debe ser documentada en esta sección
central o si sería preferible documentarla localmente (Por ejemplo, dentro de una plantilla de caja blanca
de un bloque de construcción).

Evite la redundancia. Tomar de referencia la sección 4, donde ya se capturaron las decisiones más importantes 
para la arquitectura.

.Motivación
Las partes relacionadas del sistema deben comprender y trazar las decisiones.

.Forma
Varias opciones:

* Lista o tabla, ordenada por importancia y consecuencias o:
* Mayor detalle en secciones separadas por cada sección.
* Registro de Decisiones de Arquitectura (ADR por sus siglas en inglés) para cada decisión importante.
****
endif::arc42help[]

=== Acceso a Wikidata

*Problema:*
Tenemos que acceder de alguna forma a las imágenes y etiquetas proporcionadas por Wikidata.

*Alternativas consideradas:*

* Búsqueda con Elasticsearch via la API "wbsearchentities"
* Búsqueda son SPARQL via endpoint propio de Wikidata

*Decisión tomada:*
Decidimos usar el endpoint de SPARQL ya que era la forma de acceso a los datos de Wikidata que más se ajustaba a nuestro proyecto.

=== Modelo de lenguaje usado

*Problema:*
Necesitamos usar un LLM en la aplicación para proporcionar un chat interactivo en tiempo real.

*Alternativas consideradas:*

* Gemini de Google
* Mistral de Empathy

*Decisión tomada:*
El Modelo de Lenguaje que decidimos usar será Mistral de la empresa Empathy.

=== Despliegue

*Problema:*
Necesitamos desplegar la aplicación para su uso.

*Decisión:*
La aplicación se desplegará usando Docker por la flexibilidad para desplegar en distintas plataformas.