ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Decisiones de Diseño


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
endif::arc42help[]

=== Acceso a Wikidata

*Problema:*
Tenemos que acceder de alguna forma a las imágenes y etiquetas proporcionadas por Wikidata.

*Alternativas consideradas:*

* Búsqueda con Elasticsearch via la API "wbsearchentities"
* Búsqueda son SPARQL via endpoint propio de Wikidata

*Decisión tomada:*
Decidimos usar el endpoint de SPARQL ya que era la forma de acceso a los datos de Wikidata que más se ajustaba a nuestro proyecto.

=== Modelo de lenguaje usado

*Problema:*
Necesitamos usar un LLM en la aplicación para proporcionar un chat interactivo en tiempo real.

*Alternativas consideradas:*

* Gemini de Google
* Mistral de Empathy

*Decisión tomada:*
El Modelo de Lenguaje que decidimos usar será Mistral de la empresa Empathy.

=== Despliegue

*Problema:*
Necesitamos desplegar la aplicación para su uso.

*Decisión:*
La aplicación se desplegará usando Docker por la flexibilidad para desplegar en distintas plataformas.