ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Requerimientos de Calidad


ifdef::arc42help[]
[role="arc42help"]
****

.Content
This section contains all quality requirements as quality tree with scenarios. The most important ones have already been described in section 1.2. (quality goals)

Here you can also capture quality requirements with lesser priority,
which will not create high risks when they are not fully achieved.

.Motivation
Since quality requirements will have a lot of influence on architectural
decisions you should know for every stakeholder what is really important to them,
concrete and measurable.


.Further Information

See https://docs.arc42.org/section-10/[Quality Requirements] in the arc42 documentation.

****
endif::arc42help[]

=== Árbol de Calidad
ifdef::arc42help[]
[role="arc42help"]
****
.Content
The quality tree (as defined in ATAM – Architecture Tradeoff Analysis Method) with quality/evaluation scenarios as leafs.

.Motivation
The tree structure with priorities provides an overview for a sometimes large number of quality requirements.

.Form
The quality tree is a high-level overview of the quality goals and requirements:

* tree-like refinement of the term "quality". Use "quality" or "usefulness" as a root
* a mind map with quality categories as main branches

In any case the tree should include links to the scenarios of the following section.


****
endif::arc42help[]

[plantuml, árbol de calidad, png]
----
@startuml
@startmindmap
+ Atributos de calidad
++ Usabilidad
+++ El juego debe ser fácil de jugar
+++ La interacción con el LLM debe ser sencilla
++ Rendimiento
+++ Las preguntas deben cargar en poco tiempo
++ Compatibilidad
+++ La aplicación debe funcionar en distintos navegadores
+++ La aplicación debe funcionar en distintos dispositivos
++ Privacidad
+++ La contraseñas deben estar encriptadas
+++ El usuario sólo tiene acceso a sus datos
++ Accesibilidad
+++ Los textos de la iinterfaz tienen que tener un tamaño mínimo
++ Mantenibilidad
+++ Las pruebas deben estar automatizadas
@endmindmap
@enduml
----

=== Escenarios de calidad

ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Concretization of (sometimes vague or implicit) quality requirements using (quality) scenarios.

These scenarios describe what should happen when a stimulus arrives at the system.

For architects, two kinds of scenarios are important:

* Usage scenarios (also called application scenarios or use case scenarios) describe the system’s runtime reaction to a certain stimulus. This also includes scenarios that describe the system’s efficiency or performance. Example: The system reacts to a user’s request within one second.
* Change scenarios describe a modification of the system or of its immediate environment. Example: Additional functionality is implemented or requirements for a quality attribute change.

.Motivation
Scenarios make quality requirements concrete and allow to
more easily measure or decide whether they are fulfilled.

Especially when you want to assess your architecture using methods like
ATAM you need to describe your quality goals (from section 1.2)
more precisely down to a level of scenarios that can be discussed and evaluated.

.Form
Tabular or free form text.
****
endif::arc42help[]

==== Escenarios de uso
|===
| **Atributo de calidad** | **Escenario**
| _Usabilidad_ | El usuario debe poder entender cómo jugar al juego en un máximo de 10 minutos sin tener conocimientos previos.
| _Usabilidad_ | El usuario debe poder pedir pistas al LLM sin tener conocimientos previos acerca de cómo utilizar una IA. 
| _Rendimiento_ | El sistema debe cargar las preguntas en menos de 2s.
| _Compatibilidad_ | La aplicación debe funcionar en las versiones más nuevas de los navegadores más utilizados (Chrome, Firefox, Edge...).
| _Compatibilidad_ | La aplicación debe funcionar en distintos dispositivos (móvil, tablet y ordenador).
| _Privacidad_ | Las contraseñas de los usuarios deben guardarse encriptadas en la base de datos.
| _Privacidad_ | El usuario sólo debe tener acceso a sus propios datos. El sistema debe evitar que un usuario logre acceder a los datos de otros usuarios.
| _Accesibilidad_ | Los textos de la interfaz deben tener un tamaño mínimo de 16px para garantizar que sean legibles.
|===
==== Escenarios de cambios
|===
| **Atributo de calidad** | **Escenario**
| _Mantenibilidad_ | Las pruebas deben estar automatizadas de modo que cuando se añada una nueva funcionalidad se pueda comprobar fácilmente que la funcionalidad anterior sigue funcionando. 
| _Mantenibilidad_ | El código debe estar bien documentado y separado en distintos módulos, permitiendo fácilmente modificaciones.
|===


