ifndef::imagesdir[:imagesdir: ../images]

[[section-quality-scenarios]]
== Requerimientos de Calidad


ifdef::arc42help[]
[role="arc42help"]
****

Esta sección describe todos los requerimientos de calidad como un árbol de calidad con escenarios. Los más importantes ya han sido descritos en la sección 1.2 (Metas de Calidad).
Aquí se capturan los requerimientos de calidad con menor prioridad, que no crearán altos riesgos en caso de que no sean cubiertos con totalidad.

.Motivación
Dado que los requerimientos de calidad tendrán mucha influencia en las decisiones arquitectónicas deben tomarse en cuenta los elementos importantes para las partes relacionadas que sean concretas y medibles.

.Más información

Vea  https://docs.arc42.org/section-10/[Quality Requirements] en la documentación de arc42.

****
endif::arc42help[]

=== Árbol de Calidad
ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
El árbol de calidad (Definido en ATAM - Método de análisis de compensación de arquitectura por sus silas en inglés) con escenarios de calidad/evaluación como hojas.

.Motivación
La estructura de árbol con prioridades provee un vistazo general para un gran número de requerimientos de calidad.

.Formato
El árbol de calidad es un vistazo a alto nivel de las metas de calidad y requerimientos:
* Un refinamiento del término de "calidad" a manera de árbol. Utilice "calidad" o "utilidad" como raíz.
* Un mapa mental con categorías de calidad como ramas principales
En cualquier caso incluya ligas a los escenarios de las siguientes secciones.

****
endif::arc42help[]

[plantuml, árbol de calidad, png]
----
@startuml
@startmindmap
+ Atributos de calidad
++ Usabilidad
+++ El juego debe ser fácil de jugar
+++ La interacción con el LLM debe ser sencilla
++ Rendimiento
+++ Las preguntas deben cargar en poco tiempo
++ Compatibilidad
+++ La aplicación debe funcionar en distintos navegadores
+++ La aplicación debe funcionar en distintos dispositivos
++ Privacidad
+++ La contraseñas deben estar encriptadas
+++ El usuario sólo tiene acceso a sus datos
++ Accesibilidad
+++ Los textos de la interfaz deben tener un tamaño mínimo
++ Mantenibilidad
+++ Las pruebas deben estar automatizadas
@endmindmap
@enduml
----

=== Escenarios de calidad

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Concretización de requerimientos de calidad (que pueden ser vagos o implícitos) utilizando escenarios de calidad.
Estos escenarios describen lo que debería pasar cuando un estímulo llega al sistema.
Para los arquitectos, son importantes dos tipos de escenarios:
* Escenarios de uso (también llamados escenarios de aplicación o escenarios de caso de uso), que describen la reacción en tiempo de ejecución de un sistema a un determinado estímulo. Esto incluye también escenarios que describen la eficiencia o el rendimiento del sistema. Por ejemplo: El sistema reacciona a la petición de un usuario en un segundo.
* Escenarios de cambios, describen la modificación del sistema a su ambiente inmediato. Por ejemplo: Cuando se implementa funcionalidad adicional o requerimientos para el cambio de un atributo de calidad.

.Motivación
Los escenarios crean requerimientos de calidad concretos y permiten medirlos de manera más sencilla o decidir si han sido cumplidos.
Cuando se requiere evaluar la arquitectura utilizando métodos como ATAM se necesitan describir las metas de calidad (de la sección 1.2) de manera más precisa hasta un nivel de escenarios que pueden ser discutidos y evaluados.

.Formato
Texto en forma libre o tabular.
****
endif::arc42help[]

==== Escenarios de uso
|===
| **Atributo de calidad** | **Escenario**
| _Usabilidad_ | El usuario debe poder entender cómo jugar al juego en un máximo de 10 minutos sin tener conocimientos previos.
| _Usabilidad_ | El usuario debe poder pedir pistas al LLM sin tener conocimientos previos acerca de cómo utilizar una IA. 
| _Rendimiento_ | El sistema debe cargar las preguntas en menos de 2s.
| _Compatibilidad_ | La aplicación debe funcionar en las versiones más nuevas de los navegadores más utilizados (Chrome, Firefox, Edge...).
| _Compatibilidad_ | La aplicación debe funcionar en distintos dispositivos (móvil, tablet y ordenador).
| _Privacidad_ | Las contraseñas de los usuarios deben guardarse encriptadas en la base de datos.
| _Privacidad_ | El usuario sólo debe tener acceso a sus propios datos. El sistema debe evitar que un usuario logre acceder a los datos de otros usuarios.
| _Accesibilidad_ | Los textos de la interfaz deben tener un tamaño mínimo de 16px para garantizar que sean legibles.
|===
==== Escenarios de cambios
|===
| **Atributo de calidad** | **Escenario**
| _Mantenibilidad_ | Las pruebas deben estar automatizadas de modo que cuando se añada una nueva funcionalidad se pueda comprobar fácilmente que la funcionalidad anterior sigue funcionando. 
| _Mantenibilidad_ | El código debe estar bien documentado y separado en distintos módulos, permitiendo fácilmente modificaciones.
|===
