ifndef::imagesdir[:imagesdir: ../images]

[[section-technical-risks]]
== Risks and Technical Debts


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.


.Further Information

See https://docs.arc42.org/section-11/[Risks and Technical Debt] in the arc42 documentation.

****
endif::arc42help[]

=== Riesgos

[options="header",cols="1,2,2,2"]
|===
|Riesgo|Descripción|Impacto|Mitigación
| _Abandono de componentes del equipo_ | _<Descripción 1>_ | _<Impacto 1>_ | _<Mitigación 1>_
| _<Riesgo 2>_ | _<Descripción 2>_ | _<Impacto 2>_ | _<Mitigación 2>_
|===

=== Deuda Técnica

[options="header",cols="1,2,2,2"]
|===
|Deuda Técnica|Descripción|Consecuencia|Mitigación
| _<Deuda 1>_ | _<Descripción 1>_ | _<Consecuencia 1>_ | _<Mitigación 1>_
| _<Deuda 2>_ | _<Descripción 2>_ | _<Consecuencia 2>_ | _<Mitigación 2>_
|===